language: dotnet
dotnet_version: "10.0.x"
dotnet_solution: "InfraGate.slnx"
project: "infragate"
package_ecosystems:
  - "nuget"
  - "github-actions"
use_semgrep: true
use_docker: true
use_codecov: false
coverage_provider: "sonarcloud"
release_strategy: "manual-tag"
ci_branches: ["main", "dev"]
release_branches: ["main"]
deploy_branches: ["dev"]
use_dependency_scan: true
use_sonar: true
use_container_scan: true
