#!/usr/bin/env bash
# setup-development-deploy.sh — prepares the local machine for deploy-development.
#
# Creates:
#   /etc/infra-gate/development.env       - gateway runtime environment (generated by RunProfiles)
#   /etc/infra-gate/development.appsettings.json - gateway/server runtime appsettings (generated by RunProfiles)
#   /etc/infra-gate/development.kubeconfig - Kubernetes access for the gateway
#   /var/lib/infra-gate/development/       - approvals + guardrails persistence
#
# Usage:
#   sudo ./scripts/setup-development-deploy.sh
#   sudo KEYCLOAK_PORT=3010 INFRA_GATE_GATEWAY_IMAGE=ghcr.io/... ./scripts/setup-development-deploy.sh
#
# Prerequisites:
#   - minikube running (kubeconfig auto-generated via create-demo-kubeconfig.sh)
#   - Docker, Docker Compose v2, curl, kubectl, .NET 10 SDK
#
# This script starts/updates the local Keycloak instance from
# deploy/compose/keycloak.yaml and configures the gateway to use it.
# The gateway env file at /etc/infra-gate/development.env is generated
# by InfraGate.RunProfiles from deploy/run-profiles.yaml (profile: development),
# alongside appsettings JSON with dynamic values (Docker host IP, Keycloak port)
# supplied via --set.

set -euo pipefail

REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

KEYCLOAK_PORT="${KEYCLOAK_PORT:-3010}"
GATEWAY_PORT="${GATEWAY_PORT:-3001}"

# Container-to-host networking: the gateway container reaches Keycloak on the
# host via the Docker bridge IP. Defaults to the common docker0 address.
docker_host_ip() {
  ip -4 addr show docker0 2>/dev/null \
    | awk '/inet / {print $2}' \
    | cut -d/ -f1 \
    | head -n1
}

dump_keycloak_logs() {
  KEYCLOAK_BIND_ADDRESS="$KEYCLOAK_BIND_ADDRESS" \
  KEYCLOAK_PORT="$KEYCLOAK_PORT" \
  docker compose -f "$KEYCLOAK_COMPOSE_FILE" logs --tail=50 keycloak >&2 || true
}

DOCKER_HOST_IP="$(docker_host_ip)"
DOCKER_HOST_IP="${DOCKER_HOST_IP:-172.17.0.1}"
KEYCLOAK_BIND_ADDRESS="${KEYCLOAK_BIND_ADDRESS:-0.0.0.0}"

# Clear-text HTTP is intentional for this local Debian development setup.
# Production OIDC configuration must use HTTPS outside this script.
LOCAL_HTTP_SCHEME="http" # NOSONAR
LOCAL_LOOPBACK_HOST="127.0.0.1"
LOCAL_LISTEN_HOST="0.0.0.0"
KEYCLOAK_REALM_PATH="/realms/infra-gate"
KEYCLOAK_METADATA_PATH="/.well-known/openid-configuration"
KEYCLOAK_OPENID_CONNECT_PATH="/protocol/openid-connect"
GATEWAY_MCP_PATH="/mcp"

KEYCLOAK_BASE_URL="${LOCAL_HTTP_SCHEME}://${LOCAL_LOOPBACK_HOST}:${KEYCLOAK_PORT}${KEYCLOAK_REALM_PATH}"
KEYCLOAK_CONTAINER_BASE_URL="${LOCAL_HTTP_SCHEME}://${DOCKER_HOST_IP}:${KEYCLOAK_PORT}${KEYCLOAK_REALM_PATH}"
GATEWAY_BASE_URL="${LOCAL_HTTP_SCHEME}://${LOCAL_LOOPBACK_HOST}:${GATEWAY_PORT}"
ASPNETCORE_URLS_VALUE="${LOCAL_HTTP_SCHEME}://${LOCAL_LISTEN_HOST}:3001"
OAUTH_AUTHORITY="$KEYCLOAK_BASE_URL"
OAUTH_RESOURCE="${GATEWAY_BASE_URL}${GATEWAY_MCP_PATH}"
OAUTH_METADATA_ADDRESS="${KEYCLOAK_CONTAINER_BASE_URL}${KEYCLOAK_METADATA_PATH}"
TOKEN_ENDPOINT="${KEYCLOAK_CONTAINER_BASE_URL}${KEYCLOAK_OPENID_CONNECT_PATH}/token"
AUTH_ENDPOINT="${KEYCLOAK_BASE_URL}${KEYCLOAK_OPENID_CONNECT_PATH}/auth"
APPROVAL_BASE_URL="$GATEWAY_BASE_URL"
KEYCLOAK_DISCOVERY_URL="${KEYCLOAK_BASE_URL}${KEYCLOAK_METADATA_PATH}"

INFRA_GATE_GATEWAY_IMAGE="${INFRA_GATE_GATEWAY_IMAGE:-ghcr.io/mirusser/kubernetes-mcp-guard-gateway}"
RUNNER_USER="${RUNNER_USER:-${SUDO_USER:-}}"
GATEWAY_APP_UID="1654"
GATEWAY_APP_UGID="${GATEWAY_APP_UID}:${GATEWAY_APP_UID}"

DEPLOY_PATH="${DEPLOY_PATH:-/opt/infra-gate}"
ENV_FILE="/etc/infra-gate/development.env"
APPSETTINGS_FILE="/etc/infra-gate/development.appsettings.json"
KUBECONFIG_FILE="/etc/infra-gate/development.kubeconfig"
APPROVAL_DIR="/var/lib/infra-gate/development/approvals"
GUARDRAIL_DIR="/var/lib/infra-gate/development/guardrails"
KEYCLOAK_COMPOSE_FILE="$REPO_ROOT/deploy/compose/keycloak.yaml"

usage() {
  cat <<EOF
Usage: sudo $0

Prepares the local machine for the deploy-development GitHub Actions job.

Configures OAuth for a local Keycloak instance at
${OAUTH_AUTHORITY}

Environment overrides:
  KEYCLOAK_PORT       Keycloak host port (default: ${KEYCLOAK_PORT})
  KEYCLOAK_BIND_ADDRESS
                      Keycloak host bind address (default: ${KEYCLOAK_BIND_ADDRESS})
  GATEWAY_PORT        Gateway host port (default: ${GATEWAY_PORT})
  INFRA_GATE_GATEWAY_IMAGE
                      Gateway Docker image (default: ${INFRA_GATE_GATEWAY_IMAGE})
  DEPLOY_PATH         Compose file directory (default: ${DEPLOY_PATH})
  RUNNER_USER         User that runs the self-hosted runner (default: sudo user)

Creates:
  ${ENV_FILE}
  ${KUBECONFIG_FILE}
  ${APPROVAL_DIR}
  ${GUARDRAIL_DIR}
EOF
}

if [[ $# -gt 0 ]]; then
  case "$1" in
    -h|--help)
      usage
      exit 0
      ;;
    *)
      echo "Unknown option: $1" >&2
      usage >&2
      exit 1
      ;;
  esac
fi

# ── pre-checks ────────────────────────────────────────────────────────────────

if [[ "$(id -u)" -ne 0 ]]; then
  echo "ERROR: This script must be run as root (writes to /etc and /var/lib)." >&2
  echo "  sudo $0" >&2
  exit 1
fi

command -v docker >/dev/null 2>&1 || {
  echo "ERROR: docker is required." >&2; exit 1
}

docker compose version >/dev/null 2>&1 || {
  echo "ERROR: Docker Compose v2 is required." >&2; exit 1
}

command -v curl >/dev/null 2>&1 || {
  echo "ERROR: curl is required." >&2; exit 1
}

command -v kubectl >/dev/null 2>&1 || {
  echo "ERROR: kubectl is required." >&2; exit 1
}

if [[ "$GATEWAY_PORT" != "3001" ]]; then
  echo "ERROR: GATEWAY_PORT must be 3001 for the bundled Keycloak realm." >&2
  echo "  Update deploy/keycloak/infra-gate-realm.json first if you need a different gateway port." >&2
  exit 1
fi

if [[ -n "$RUNNER_USER" ]] && ! id "$RUNNER_USER" >/dev/null 2>&1; then
  echo "ERROR: RUNNER_USER does not exist: $RUNNER_USER" >&2
  exit 1
fi

if [[ -n "$RUNNER_USER" && "$RUNNER_USER" != "root" ]] && ! command -v runuser >/dev/null 2>&1; then
  echo "ERROR: runuser is required when RUNNER_USER is not root." >&2
  exit 1
fi

# ── create directories ────────────────────────────────────────────────────────

mkdir -p "$DEPLOY_PATH"
mkdir -p "$(dirname "$ENV_FILE")"
mkdir -p "$APPROVAL_DIR"
mkdir -p "$GUARDRAIL_DIR"

if [[ -n "$RUNNER_USER" ]]; then
  chown "$RUNNER_USER:" "$DEPLOY_PATH"
fi

# Bind mounts are writable only by the non-root .NET app user used by the
# gateway image. Approval and guardrail data is mutable security state.
chown -R "$GATEWAY_APP_UGID" "$APPROVAL_DIR" "$GUARDRAIL_DIR"
chmod -R u+rwX,go-rwx "$APPROVAL_DIR" "$GUARDRAIL_DIR"

# ── runtime env file ──────────────────────────────────────────────────────────

echo "Generating $ENV_FILE from run profile (development) ..."
dotnet run --project "${REPO_ROOT}/src/InfraGate.RunProfiles" -- generate development \
  --set "gateway.aspnetcoreUrls=${ASPNETCORE_URLS_VALUE}" \
  --set "identityProvider.authority=${OAUTH_AUTHORITY}" \
  --set "identityProvider.metadataAddress=${OAUTH_METADATA_ADDRESS}" \
  --set "identityProvider.resource=${OAUTH_RESOURCE}" \
  --set "approvalAuthority.baseUrl=${APPROVAL_BASE_URL}" \
  --set "approvalAuthority.oauthAuthorizationEndpoint=${AUTH_ENDPOINT}" \
  --set "approvalAuthority.oauthTokenEndpoint=${TOKEN_ENDPOINT}" \
  --set "host.gatewayImage=${INFRA_GATE_GATEWAY_IMAGE}" \
  --set "host.bindPort=${GATEWAY_PORT}" \
  --set "host.configHostPath=${APPSETTINGS_FILE}" \
  --set "host.kubeconfigHostPath=${KUBECONFIG_FILE}" \
  --set "host.approvalHostPath=${APPROVAL_DIR}" \
  --set "host.guardAuditHostPath=${GUARDRAIL_DIR}" \
  --force \
  --output "${ENV_FILE}"

chmod 600 "$ENV_FILE"
if [[ -n "$RUNNER_USER" ]]; then
  chown "$RUNNER_USER:" "$ENV_FILE"
fi
echo "Created $ENV_FILE"

echo "Generating $APPSETTINGS_FILE from run profile (development) ..."
dotnet run --project "${REPO_ROOT}/src/InfraGate.RunProfiles" -- generate development \
  --format appsettings \
  --set "gateway.aspnetcoreUrls=${ASPNETCORE_URLS_VALUE}" \
  --set "identityProvider.authority=${OAUTH_AUTHORITY}" \
  --set "identityProvider.metadataAddress=${OAUTH_METADATA_ADDRESS}" \
  --set "identityProvider.resource=${OAUTH_RESOURCE}" \
  --set "approvalAuthority.baseUrl=${APPROVAL_BASE_URL}" \
  --set "approvalAuthority.oauthAuthorizationEndpoint=${AUTH_ENDPOINT}" \
  --set "approvalAuthority.oauthTokenEndpoint=${TOKEN_ENDPOINT}" \
  --force \
  --output "${APPSETTINGS_FILE}"

chown "$GATEWAY_APP_UGID" "$APPSETTINGS_FILE"
chmod 640 "$APPSETTINGS_FILE"
echo "Created $APPSETTINGS_FILE"

# ── kubeconfig ────────────────────────────────────────────────────────────────

echo "Generating kubeconfig via create-demo-kubeconfig.sh ..."
if [[ -n "$RUNNER_USER" && "$RUNNER_USER" != "root" ]]; then
  mkdir -p "$REPO_ROOT/.kube"
  chown -R "$RUNNER_USER:" "$REPO_ROOT/.kube"
  runuser -u "$RUNNER_USER" -- "$REPO_ROOT/scripts/create-demo-kubeconfig.sh"
else
  "$REPO_ROOT/scripts/create-demo-kubeconfig.sh"
fi

KUBECONFIG_SRC="$REPO_ROOT/.kube/mcp-nginx-demo.config"
if [[ -f "$KUBECONFIG_SRC" ]]; then
  cp "$KUBECONFIG_SRC" "$KUBECONFIG_FILE"
  chmod 600 "$KUBECONFIG_FILE"
  chown "$GATEWAY_APP_UGID" "$KUBECONFIG_FILE"
  echo "Copied $KUBECONFIG_SRC to $KUBECONFIG_FILE"
else
  echo "WARNING: kubeconfig not found at $KUBECONFIG_SRC." >&2
  echo "  You can create one with: scripts/create-demo-kubeconfig.sh" >&2
  echo "  Then copy it to: $KUBECONFIG_FILE" >&2
fi

# ── Keycloak ──────────────────────────────────────────────────────────────────

echo "Starting local Keycloak via $KEYCLOAK_COMPOSE_FILE ..."
KEYCLOAK_BIND_ADDRESS="$KEYCLOAK_BIND_ADDRESS" \
KEYCLOAK_PORT="$KEYCLOAK_PORT" \
docker compose -f "$KEYCLOAK_COMPOSE_FILE" up -d keycloak

echo "Waiting for Keycloak discovery at $KEYCLOAK_DISCOVERY_URL ..."
elapsed=0
while true; do
  if curl -fsS "$KEYCLOAK_DISCOVERY_URL" >/dev/null; then # NOSONAR
    break
  fi

  if [[ "$elapsed" -ge 120 ]]; then
    echo "ERROR: Keycloak did not become ready within 120 seconds." >&2
    dump_keycloak_logs
    exit 1
  fi

  sleep 2
  elapsed=$((elapsed + 2))
done
echo "Keycloak is ready."

echo "Verifying Keycloak discovery from Docker containers at $OAUTH_METADATA_ADDRESS ..."
elapsed=0
while true; do
  if docker run --rm alpine/curl -fsS "$OAUTH_METADATA_ADDRESS" >/dev/null 2>&1; then # NOSONAR
    break
  fi

  if [[ "$elapsed" -ge 60 ]]; then
    echo "ERROR: Keycloak is not reachable from Docker containers at $OAUTH_METADATA_ADDRESS." >&2
    dump_keycloak_logs
    exit 1
  fi

  sleep 2
  elapsed=$((elapsed + 2))
done
echo "Keycloak is reachable from Docker containers."

# ── summary ───────────────────────────────────────────────────────────────────

echo ""
echo "=== Setup complete =========================================="
echo ""
echo "Deploy path:     $DEPLOY_PATH"
echo "Env file:        $ENV_FILE"
echo "Kubeconfig:      $KUBECONFIG_FILE"
echo "Approvals:       $APPROVAL_DIR"
echo "Guard audit:     $GUARDRAIL_DIR"
echo ""
echo "Keycloak base:   $OAUTH_AUTHORITY"
echo "  (container reaches Keycloak at $DOCKER_HOST_IP:$KEYCLOAK_PORT)"
echo "Gateway image:   $INFRA_GATE_GATEWAY_IMAGE"
echo ""
echo "=== GitHub Configuration ===================================="
echo ""
echo "In repo Settings → Environments → 'development', optionally add:"
echo ""
echo "  Environment variable:"
echo "    DEPLOY_PATH = $DEPLOY_PATH  # defaults to /opt/infra-gate in the workflow"
echo ""
echo "No secrets are required (the job uses \${{ secrets.GITHUB_TOKEN }})."
echo ""
echo "=== Next Steps =============================================="
echo ""
echo "1. Push to 'dev' to trigger the deploy-development workflow."
echo ""
echo "2. After deploy, the gateway listens on $GATEWAY_BASE_URL"
